sudo: required
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
before_install:
  - docker pull docker.sunet.se/library/postgres-9.6:latest
  - docker pull docker.sunet.se/library/memcached:latest
services:
  - docker
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install --index-url https://pypi.sunet.se -r requirements/testing.txt
# command to run tests
script:
  - pip freeze
  - python manage.py test --settings=flog.settings.testing

