# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduroamevent',
            name='successful',
            field=models.BooleanField(db_index=True),
        ),
    ]
