# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170922_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedDailyEduroamEventAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('calling_station_id_count', models.BigIntegerField(default=0)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_daily_events', to='event.EduroamRealm')),
                ('visited_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_daily_events', to='event.EduroamRealm')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='optimizeddailyeduroameventaggregation',
            unique_together=set([('date', 'realm', 'visited_institution')]),
        ),
    ]
